<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import { storeToRefs } from "pinia";
import { useRoute, useRouter } from "vue-router";
import { Activity, Archive, Bot, Check, ChevronRight, CircleCheck, CircleGauge, CircleX, Clock3, Cpu, Database, FileText, Filter, FolderOpen, Gauge, HardDrive, LayoutDashboard, MemoryStick, Network, Pause, Pin, Play, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Terminal, Trash2, TriangleAlert, Wrench, X, Zap, ZoomIn } from "@lucide/vue";
import { invoke } from "@tauri-apps/api/core";
import { revealItemInDir } from "@tauri-apps/plugin-opener";
import type { AppSettings, CapabilityReport, Dashboard, DiagnosticCapability, Incident, IncidentDetail, IncidentDraft, Observation, RecoveryCandidate, Symptom } from "./types";
import { useAppStore } from "./stores/app";
import "./styles.css";

type Page = "dashboard"|"incidents"|"capabilities"|"privacy"|"settings";
const route = useRoute(), router = useRouter();
const page = computed<Page>({get:()=>{const value=route.params.section;return typeof value==="string"&&["dashboard","incidents","capabilities","privacy","settings"].includes(value)?value as Page:"dashboard"},set:value=>{void router.push(`/${value}`);if(value==="capabilities"&&!capabilityReport.value)void loadCapabilities()}});
const modal = ref(false), pendingTriggerTime = ref<string|null>(null), busy = ref(false), query = ref(""), tab = ref("summary"), errorMessage = ref(""), saved = ref(false);
const appStore = useAppStore();
const { dashboard, incidents, settings } = storeToRefs(appStore);
const selected = ref<IncidentDetail|null>(null);
const recovery = ref<RecoveryCandidate|null>(null);
const capabilityReport = ref<CapabilityReport|null>(null), capabilityLoading = ref(false);
const timelineZoom = ref<720 | 300 | 120>(720), visibleTracks = ref(["CPU","内存","磁盘","网络","事件"]), focusedEvidence = ref<Observation|null>(null);
const draft = ref<IncidentDraft>({symptom:"system_freeze",severity:"high",duration_seconds:10,still_happening:false,description:""});
const nav = [{id:"dashboard",label:"概览",icon:LayoutDashboard},{id:"incidents",label:"事故记录",icon:Archive},{id:"capabilities",label:"诊断能力",icon:Wrench},{id:"privacy",label:"隐私与数据",icon:ShieldCheck},{id:"settings",label:"设置",icon:Settings}] as const;
const capabilityCategories=["运行环境","基础采集","高级诊断","本地分析"];
const symptoms:{value:Symptom,label:string,icon:typeof Activity}[]=[{value:"system_slow",label:"系统卡顿",icon:Gauge},{value:"system_freeze",label:"系统无响应",icon:Pause},{value:"app_hang",label:"程序无响应",icon:Activity},{value:"network_slow",label:"网速慢",icon:Network},{value:"network_offline",label:"网络断开",icon:Zap},{value:"display_issue",label:"显示异常",icon:TriangleAlert},{value:"auto_restart",label:"自动重启",icon:RefreshCw},{value:"blue_screen",label:"蓝屏",icon:TriangleAlert},{value:"other",label:"其他",icon:FileText}];
const filtered=computed(()=>incidents.value.filter(x=>(x.symptom_label+(x.likely_cause||"")).includes(query.value)));
const fmt=(v:number)=>{
  if(v<1024)return `${Math.round(v)} B`;
  if(v<1048576)return `${(v/1024).toFixed(1)} KB`;
  if(v<1073741824)return `${(v/1048576).toFixed(v<10485760?2:1)} MB`;
  return `${(v/1073741824).toFixed(2)} GB`;
};
const date=(v:string)=>new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const status=(v:string)=>({capturing:"采集事故后窗口",freezing:"冻结证据",extracting:"提取事实",ready_for_analysis:"待分析",analyzing:"分析中",completed:"已完成",failed:"处理失败"} as Record<string,string>)[v]||v;
const sourceLabel=(v:string)=>({manual:"主界面",shortcut:"全局快捷键",tray:"系统托盘",recovery:"异常会话恢复",automatic:"自动触发"} as Record<string,string>)[v]||v;
const call=<T,>(cmd:string,args?:Record<string,unknown>)=>invoke<T>(cmd,args);
function message(value:unknown){return typeof value==="string"?value:value instanceof Error?value.message:"操作失败"}
async function refresh(){try{[dashboard.value,incidents.value]=await Promise.all([call<Dashboard>("get_dashboard"),call<Incident[]>("list_incidents")]);if(selected.value)selected.value=await call("get_incident",{id:selected.value.incident.id})}catch(error){errorMessage.value=message(error)}}
async function loadCapabilities(){capabilityLoading.value=true;try{capabilityReport.value=await call<CapabilityReport>("get_diagnostic_capabilities")}catch(error){errorMessage.value=message(error)}finally{capabilityLoading.value=false}}
async function toggle(){busy.value=true;try{dashboard.value=await call("set_monitoring",{enabled:!dashboard.value.monitoring})}catch(error){errorMessage.value=message(error)}finally{busy.value=false}}
function openIncidentModal(){pendingTriggerTime.value=new Date().toISOString();modal.value=true}
async function create(){busy.value=true;try{selected.value=await call("create_incident",{draft:draft.value,triggerTime:pendingTriggerTime.value});modal.value=false;pendingTriggerTime.value=null;page.value="incidents";await refresh()}catch(error){errorMessage.value=message(error)}finally{busy.value=false}}
async function open(id:string){try{selected.value=await call("get_incident",{id});page.value="incidents";tab.value="summary"}catch(error){errorMessage.value=message(error)}}
async function analyze(){if(!selected.value)return;busy.value=true;try{selected.value=await call("analyze_incident",{id:selected.value.incident.id});await refresh()}catch(error){errorMessage.value=message(error)}finally{busy.value=false}}
async function togglePin(){if(!selected.value)return;try{selected.value=await call("set_incident_pinned",{id:selected.value.incident.id,pinned:!selected.value.pinned})}catch(error){errorMessage.value=message(error)}}
async function remove(id:string){if(confirm("永久删除这条事故及其全部证据？")){await call("delete_incident",{id});selected.value=null;await refresh()}}
async function removeAll(){if(confirm("永久删除所有循环日志、事故包和诊断索引？设置会保留，此操作无法撤销。")){try{dashboard.value=await call("delete_all_data");selected.value=null;await refresh()}catch(error){errorMessage.value=message(error)}}}
async function save(){try{settings.value=await call("save_settings",{settings:settings.value});saved.value=true;setTimeout(()=>saved.value=false,1800)}catch(error){errorMessage.value=message(error)}}
async function resolveRecovery(create:boolean){try{const detail=await call<IncidentDetail|null>("resolve_recovery",{create});recovery.value=null;if(detail){selected.value=detail;page.value="incidents"}}catch(error){errorMessage.value=message(error)}}
async function reveal(path:string){try{await revealItemInDir(path)}catch(error){errorMessage.value=message(error)}}
function toggleTrack(label:string){visibleTracks.value=visibleTracks.value.includes(label)?visibleTracks.value.filter(value=>value!==label):[...visibleTracks.value,label]}
function timelinePosition(offsetMs:number){const windows={720:[-600,120],300:[-240,60],120:[-90,30]} as const;const [start,end]=windows[timelineZoom.value];const seconds=offsetMs/1000;return seconds<start||seconds>end?-1:(seconds-start)/(end-start)*100}
function focusEvidence(id:string){focusedEvidence.value=selected.value?.observations.find(item=>item.id===id)||null}
const capabilityStatus=(value:DiagnosticCapability["status"])=>({available:"可用",degraded:"运行异常",unavailable:"不可用",permission_required:"权限不足",not_installed:"未安装",misconfigured:"配置错误",disabled:"未启用"} as const)[value];
const capabilityIcon=(item:DiagnosticCapability)=>item.id==="ollama"?Bot:item.id==="elevation"?ShieldCheck:["pdh","memory_api","ip_helper"].includes(item.id)?Activity:Terminal;
let timer=0;onMounted(async()=>{try{[settings.value,recovery.value]=await Promise.all([call<AppSettings>("get_settings"),call<RecoveryCandidate|null>("get_recovery_candidate")]);await refresh();if(page.value==="capabilities")await loadCapabilities();timer=setInterval(refresh,4000)}catch(error){errorMessage.value=message(error)}});onUnmounted(()=>clearInterval(timer));
</script>

<template>
<div class="shell">
  <aside><div class="brand"><span><Activity/></span><div><b>系统黑盒子</b><small>系统故障记录器</small></div></div>
    <nav><button v-for="n in nav" :class="{active:page===n.id}" @click="page=n.id;selected=null"><component :is="n.icon"/>{{n.label}}</button></nav>
    <footer><p><i :class="{live:dashboard.monitoring}"></i>{{dashboard.monitoring?"监控正在运行":"监控已暂停"}}</p><small>Ctrl + Shift + F12 快速标记</small><small>数据仅保存在此设备</small></footer>
  </aside>
  <main><header><div><h1>{{selected?"事故详情":nav.find(n=>n.id===page)?.label}}</h1><p>{{selected?`${selected.incident.symptom_label} · ${date(selected.incident.created_at)}`:page==="capabilities"?"验证诊断组件、权限与本地分析服务":"持续记录系统状态，在故障消失前留下证据"}}</p></div><button class="icon" :disabled="capabilityLoading" @click="page==='capabilities'?loadCapabilities():refresh()"><RefreshCw :class="{spinning:capabilityLoading}"/></button></header>

    <section v-if="page==='dashboard'" class="page">
      <div v-if="recovery" class="recovery"><TriangleAlert/><span><b>检测到上次运行可能异常中断</b><small>最后有效采样：{{recovery.last_sample_at?date(recovery.last_sample_at):"未知"}}</small></span><button class="secondary" @click="resolveRecovery(false)">忽略</button><button class="primary" @click="resolveRecovery(true)">创建事故记录</button></div>
      <div class="hero"><div><label><i :class="{off:!dashboard.monitoring}"></i>{{dashboard.monitoring?"正在保护当前会话":"当前未记录系统状态"}}</label><h2>电脑刚才出现了问题？</h2><p>立即保存故障前 10 分钟与后续 2 分钟的系统证据。</p></div><button class="incident" @click="openIncidentModal"><Plus/>刚才发生了问题</button></div>
      <div class="metrics"><article v-for="m in [{n:'CPU',v:dashboard.cpu_percent,u:'%',max:100,i:Cpu},{n:'内存',v:dashboard.memory_percent,u:'%',max:100,i:MemoryStick},{n:'磁盘延迟',v:dashboard.disk_latency_ms,u:' ms',max:500,i:HardDrive},{n:'网络',v:dashboard.network_kbps,u:' KB/s',max:10240,i:Network}]"><div><component :is="m.i"/><span>{{m.n}}</span><b>{{m.v.toFixed(0)}}{{m.u}}</b></div><div class="meter"><i :style="{width:`${Math.min(100,m.v/m.max*100)}%`}"></i></div><small>最近一次本地采样</small></article></div>
      <div class="columns"><article class="panel"><div class="panel-title"><div><h3>采集状态</h3><p>低开销后台记录</p></div><button :class="dashboard.monitoring?'secondary':'primary'" @click="toggle"><Pause v-if="dashboard.monitoring"/><Play v-else/>{{dashboard.monitoring?"暂停":"开始监控"}}</button></div>
        <dl><div><dt><Clock3/>本次运行</dt><dd>{{Math.floor(dashboard.uptime_seconds/60)}} 分钟</dd></div><div><dt><Database/>循环数据</dt><dd>{{fmt(dashboard.storage_bytes)}} / {{settings.rolling_limit_gb}} GB</dd></div><div><dt><CircleGauge/>采样间隔</dt><dd>{{dashboard.effective_interval_seconds||settings.sample_interval_seconds}} 秒<span v-if="dashboard.effective_interval_seconds>settings.sample_interval_seconds">（开销保护已降级）</span></dd></div><div><dt><Activity/>性能循环日志</dt><dd>{{dashboard.etw_status}}</dd></div><div><dt><Zap/>全局快捷键</dt><dd>{{dashboard.shortcut_status}}</dd></div><div><dt><Cpu/>BlackBox 自身开销</dt><dd>CPU {{dashboard.blackbox_cpu_percent.toFixed(1)}}% · 内存 {{fmt(dashboard.blackbox_memory_bytes)}} · 写入 {{dashboard.blackbox_disk_write_kbps.toFixed(1)}} KB/s</dd></div></dl></article>
        <article class="panel recent"><div class="panel-title"><div><h3>最近事故</h3><p>共 {{incidents.length}} 条本地记录</p></div><button class="link" @click="page='incidents'">查看全部 <ChevronRight/></button></div>
          <p v-if="!incidents.length" class="empty"><Archive/>事故记录会显示在这里</p><button v-for="x in incidents.slice(0,3)" @click="open(x.id)"><i :class="x.severity"></i><span><b>{{x.symptom_label}}</b><small>{{date(x.created_at)}} · {{status(x.status)}}</small></span><em>{{x.likely_cause||"等待分析"}}</em><ChevronRight/></button></article></div>
    </section>

    <section v-else-if="page==='incidents'&&!selected" class="page"><div class="toolbar"><label><Search/><input v-model="query" placeholder="搜索事故或原因"></label><button class="primary" @click="openIncidentModal"><Plus/>标记事故</button></div>
      <div class="table"><div class="thead"><span>时间与症状</span><span>状态</span><span>最可能原因</span><span>可信度</span></div><button v-for="x in filtered" @click="open(x.id)"><span><i :class="x.severity"></i><b>{{x.symptom_label}}</b><small>{{date(x.created_at)}}</small></span><em>{{status(x.status)}}</em><span>{{x.likely_cause||"等待结构化分析"}}</span><span>{{x.confidence?Math.round(x.confidence*100)+"%":"—"}}</span></button><p v-if="!filtered.length" class="empty"><Archive/>没有事故记录</p></div>
    </section>

    <section v-else-if="selected" class="page"><div class="detail-head panel"><div><button class="back" @click="selected=null">← 返回事故列表</button><h2><TriangleAlert/>{{selected.incident.symptom_label}}</h2><p>{{selected.incident.id}} · {{date(selected.incident.trigger_time)}} · {{status(selected.incident.status)}}</p></div><div><button class="secondary" @click="togglePin"><Pin/>{{selected.pinned?"取消固定":"固定保留"}}</button><button class="danger" @click="remove(selected.incident.id)"><Trash2/>删除</button><button class="primary" :disabled="busy || !['ready_for_analysis','completed'].includes(selected.incident.status)" @click="analyze"><Sparkles/>{{selected.report?"重新分析":"开始分析"}}</button></div></div>
      <div v-if="['capturing','freezing','extracting'].includes(selected.incident.status)" class="processing"><RefreshCw/><span><b>{{status(selected.incident.status)}}</b> 后台正在保存事故现场，窗口可以正常关闭或切换。</span></div>
      <div v-else-if="selected.incident.status==='failed'" class="processing failed"><TriangleAlert/><span><b>证据处理失败</b> 原始事故目录已保留，可在“原始文件”中检查 pipeline-error.txt。</span></div>
      <div class="tabs"><button v-for="t in [['summary','摘要'],['timeline','时间线'],['evidence','证据'],['ai','AI 分析'],['raw','原始文件']]" :class="{active:tab===t[0]}" @click="tab=t[0]">{{t[1]}}</button></div>
      <div v-if="tab==='summary'" class="detail-grid"><article class="panel report"><label>诊断摘要</label><h2>{{selected.report?.summary||"证据已保存，等待本地分析"}}</h2><p v-if="!selected.report">规则引擎会先提取确定性事实，再由本地模型解释。</p><div v-for="(c,i) in selected.report?.likely_causes"><i>{{i+1}}</i><span><b>{{c.title}}</b><p>{{c.explanation}}</p></span><em>{{Math.round(c.confidence*100)}}%</em></div></article>
        <article class="panel facts"><h3>事故信息</h3><dl><div><dt>严重程度</dt><dd>{{selected.incident.severity}}</dd></div><div><dt>触发来源</dt><dd>{{sourceLabel(selected.incident.trigger_source)}}</dd></div><div><dt>故障前窗口</dt><dd>{{Math.round(selected.incident.pre_window_seconds/60)}} 分钟</dd></div><div><dt>故障后窗口</dt><dd>{{Math.round(selected.incident.post_window_seconds/60)}} 分钟</dd></div><div><dt>敏感等级</dt><dd>Level {{selected.incident.sensitivity_level}}</dd></div><div><dt>应用版本</dt><dd>{{selected.incident.app_version}}</dd></div></dl></article></div>
      <div v-else-if="tab==='timeline'" class="panel timeline"><div class="timeline-head"><div><h3>统一证据时间线</h3><p>0 = 用户标记故障的时刻</p></div><div class="timeline-tools"><span><ZoomIn/>范围</span><button v-for="option in [{value:720,label:'−10m / +2m'},{value:300,label:'−4m / +1m'},{value:120,label:'−90s / +30s'}]" :class="{active:timelineZoom===option.value}" @click="timelineZoom=option.value as 720|300|120">{{option.label}}</button></div></div><div class="track-filters"><span><Filter/>显示</span><button v-for="track in selected.timeline" :class="{active:visibleTracks.includes(track.label)}" @click="toggleTrack(track.label)">{{track.label}}</button></div><div v-for="track in selected.timeline.filter(item=>visibleTracks.includes(item.label))" class="timeline-row"><b>{{track.label}}</b><span><i class="trigger" :style="{left:`${timelinePosition(0)}%`}"></i><button v-for="p in track.points.filter(point=>timelinePosition(point.offset_ms)>=0)" class="timeline-point" :class="p.severity" :style="{left:`${timelinePosition(p.offset_ms)}%`}" :title="p.title" @click="focusEvidence(p.id)"></button></span></div><div v-if="focusedEvidence" class="timeline-inspector"><button class="icon" @click="focusedEvidence=null"><X/></button><b>{{focusedEvidence.title}}</b><p>{{focusedEvidence.description}}</p><code>{{focusedEvidence.id}} · {{focusedEvidence.source}} · {{focusedEvidence.offset_ms/1000}}s</code></div></div>
      <div v-else-if="tab==='evidence'" class="panel evidence"><h3>结构化观察结果</h3><div v-for="o in selected.observations"><Activity/><span><b>{{o.title}}</b><p>{{o.description}}</p><code>{{o.id}} · {{o.source}} · {{o.offset_ms/1000}}s</code></span><em :class="o.severity">{{o.severity}}</em></div><p v-if="!selected.observations.length" class="empty">未提取到异常</p></div>
      <div v-else-if="tab==='ai'" class="panel ai"><Bot/><h3>本地 AI 诊断</h3><p>AI 只能解释已有证据，不能修改数据或执行修复。</p><h2>{{selected.report?.summary||"尚未生成报告"}}</h2></div>
      <div v-else class="panel raw"><h3>事故包文件</h3><p><ShieldCheck/>这些文件不会自动上传。</p><div v-for="f in selected.raw_files"><FileText/><span><b>{{f.name}}</b><small>{{f.kind}}</small></span><em>{{fmt(f.size_bytes)}}</em></div><code>{{selected.data_path}}</code><button class="secondary reveal" @click="reveal(selected.data_path)"><FolderOpen/>在文件资源管理器中定位</button></div>
    </section>

    <section v-else-if="page==='capabilities'" class="page capabilities-page">
      <div v-if="capabilityReport" class="capability-overview panel"><div><span :class="['capability-health',{warning:capabilityReport.attention}]"><CircleCheck v-if="!capabilityReport.attention"/><TriangleAlert v-else/></span><div><h2>{{capabilityReport.attention?`${capabilityReport.attention} 项基础能力需要处理`:"基础诊断能力正常"}}</h2><p>{{capabilityReport.available}} 项能力可用 · 当前进程{{capabilityReport.is_elevated?"已提升权限":"未提升权限"}} · 检测于 {{date(capabilityReport.checked_at)}}</p></div></div><button class="secondary" :disabled="capabilityLoading" @click="loadCapabilities"><RefreshCw :class="{spinning:capabilityLoading}"/>重新检测</button></div>
      <div v-else class="panel capability-loading"><RefreshCw class="spinning"/><span><b>正在检测诊断能力</b><small>只检查本机组件、权限与已配置的本地服务。</small></span></div>
      <article v-for="category in capabilityCategories" v-if="capabilityReport" class="panel capability-group"><header><div><h3>{{category}}</h3><p>{{category==="基础采集"?"当前版本直接依赖的系统采集能力":category==="高级诊断"?"后续阶段按需启用，不影响基础记录":category==="本地分析"?"只连接设置中明确配置的本机服务":"影响受保护诊断功能的运行条件"}}</p></div><span>{{capabilityReport.capabilities.filter(item=>item.category===category&&item.status==="available").length}} / {{capabilityReport.capabilities.filter(item=>item.category===category).length}} 可用</span></header>
        <div v-for="item in capabilityReport.capabilities.filter(item=>item.category===category)" class="capability-row"><span :class="['capability-icon',item.status]"><component :is="capabilityIcon(item)"/></span><div class="capability-main"><div><b>{{item.name}}</b><span v-if="item.required_now" class="required-tag">当前使用</span><span v-else class="optional-tag">可选</span></div><p>{{item.usage}}</p><small>{{item.detail}}</small><code v-if="item.path">{{item.path}}</code><aside v-if="item.recommendation"><TriangleAlert/>{{item.recommendation}}</aside></div><div class="capability-state"><span :class="item.status"><CircleCheck v-if="item.status==='available'"/><CircleX v-else-if="['unavailable','degraded','misconfigured'].includes(item.status)"/><TriangleAlert v-else/>{{capabilityStatus(item.status)}}</span><small v-if="item.requires_admin">需要管理员权限</small><small v-if="item.version">{{item.version}}</small></div></div>
      </article>
    </section>

    <section v-else-if="page==='privacy'" class="page"><div class="privacy panel"><ShieldCheck/><div><h2>默认零上传</h2><p>无需账号、无遥测。原始日志与事故包始终保存在此设备。</p></div></div><div class="columns"><article class="panel"><h3>当前收集的数据</h3><ul><li><Check/>CPU、内存、磁盘性能指标 <em>Level 0</em></li><li><Check/>进程与事件 Provider <em>Level 1</em></li><li><X/>键盘、屏幕、文件内容 <em>不收集</em></li></ul><p>当前最高敏感等级：Level {{dashboard.sensitivity_level_max}}</p></article><article class="panel"><h3>本地存储</h3><p>{{incidents.length}} 条事故 · 事故包 {{fmt(dashboard.incident_storage_bytes)}} · 循环数据 {{fmt(dashboard.storage_bytes)}}</p><code class="data-path">{{dashboard.data_path}}</code><div class="storage-actions"><button class="secondary" @click="reveal(dashboard.data_path)"><FolderOpen/>定位数据目录</button><button class="danger" @click="removeAll"><Trash2/>删除所有本地数据</button></div></article></div></section>
    <section v-else class="page settings"><article class="panel"><h3>监控与存储</h3><label><span><b>采样间隔</b><small>较短间隔开销更高</small></span><select v-model.number="settings.sample_interval_seconds"><option v-for="n in [1,2,5,10]" :value="n">{{n}} 秒</option></select></label><label><span><b>事故保留期限</b><small>固定的事故不受期限和配额清理影响。</small></span><select v-model.number="settings.retention_days"><option v-for="n in [7,30,90]" :value="n">{{n}} 天</option><option :value="0">永久</option></select></label><label><span><b>循环数据上限</b><small>达到限制后覆盖最旧的低成本性能记录。</small></span><select v-model.number="settings.rolling_limit_gb"><option v-for="n in [1,2,4,8]" :value="n">{{n}} GB</option></select></label><label><span><b>事故数据总上限</b></span><select v-model.number="settings.incident_limit_gb"><option v-for="n in [10,20,50,100]" :value="n">{{n}} GB</option></select></label></article><article class="panel"><h3>本地 AI</h3><label><span><b>分析模式</b><small>仅允许连接本机端点，原始证据不会发送。</small></span><select v-model="settings.ai_mode"><option value="disabled">无 AI（确定性规则）</option><option value="ollama">Ollama 本地模型</option></select></label><label><span><b>服务地址</b></span><input v-model="settings.ollama_endpoint"></label><label><span><b>模型</b></span><input v-model="settings.ollama_model"></label></article><article class="panel"><h3>高敏感数据</h3><label><span><b>程序 Dump</b><small>可能包含密码、令牌和文档内容；MVP 固定关闭。</small></span><b class="disabled-state">已关闭</b></label></article><button class="primary save" @click="save"><Check/>{{saved?"已保存":"保存设置"}}</button></section>
  </main>
</div>

<div v-if="errorMessage" class="toast"><TriangleAlert/><span>{{errorMessage}}</span><button class="icon" @click="errorMessage=''"><X/></button></div>

<div v-if="modal" class="backdrop" @click.self="modal=false"><form class="modal" @submit.prevent="create"><header><div><Zap/><span><h2>标记刚才的问题</h2><p>触发时刻已记录，补充信息即可保存现场。</p></span></div><button type="button" class="icon" @click="modal=false"><X/></button></header><fieldset><legend>发生了什么？</legend><div class="symptoms"><button v-for="s in symptoms" type="button" :class="{active:draft.symptom===s.value}" @click="draft.symptom=s.value"><component :is="s.icon"/>{{s.label}}</button></div></fieldset><div class="form-row"><label>严重程度<select v-model="draft.severity"><option value="low">轻微</option><option value="medium">中等</option><option value="high">严重</option><option value="critical">系统不可用</option></select></label><label>持续多久<select v-model.number="draft.duration_seconds"><option :value="5">少于 10 秒</option><option :value="30">约 30 秒</option><option :value="120">1–2 分钟</option></select></label></div><label>补充描述（可选）<textarea v-model="draft.description" maxlength="1000" placeholder="例如：切换窗口时整个系统冻结…"></textarea></label><footer><span><ShieldCheck/>数据仅保存在本机</span><button class="primary" :disabled="busy"><Activity/>保存事故现场</button></footer></form></div>
</template>
