export type Symptom = "system_slow" | "system_freeze" | "app_hang" | "network_slow" | "network_offline" | "display_issue" | "auto_restart" | "blue_screen" | "other";
export interface Dashboard { monitoring: boolean; uptime_seconds: number; storage_bytes: number; incident_storage_bytes: number; storage_limit_bytes: number; etw_status: string; cpu_percent: number; memory_percent: number; disk_latency_ms: number; network_kbps: number; last_sample_at: string | null; data_path: string; sensitivity_level_max: number; blackbox_cpu_percent: number; blackbox_memory_bytes: number; blackbox_disk_write_kbps: number; effective_interval_seconds: number; shortcut_status: string }
export interface IncidentDraft { symptom: Symptom; severity: "low" | "medium" | "high" | "critical"; duration_seconds: number; still_happening: boolean; description: string }
export interface Incident { schema_version: number; id: string; created_at: string; trigger_time: string; trigger_source: "manual" | "shortcut" | "tray" | "recovery" | "automatic"; symptom: Symptom; symptom_label: string; severity: string; status: string; pre_window_seconds: number; post_window_seconds: number; likely_cause: string | null; confidence: number | null; sensitivity_level: number; machine_id: string; app_version: string }
export interface Observation { id: string; title: string; description: string; source: string; category: string; offset_ms: number; severity: "info" | "warning" | "critical"; value: number | null; unit: string | null }
export interface Report { summary: string; likely_causes: { title: string; confidence: number; explanation: string; supporting_evidence_ids: string[] }[]; next_tests: { title: string; description: string; priority: number }[]; generated_by: string }
export type CollectionStatus = "available" | "pending" | "missing" | "failed";
export interface CollectionCategory { id: string; label: string; description: string; status: CollectionStatus; quantity: string; coverage: string | null; sensitivity_level: number; size_bytes: number; source_files: string[]; details: { label: string; value: string }[] }
export interface CollectionSummary { status: "complete" | "pending" | "partial" | "failed"; planned_window: string; actual_coverage: string; sample_count: number; event_count: number; total_size_bytes: number; sensitivity_level: number; categories: CollectionCategory[] }
export interface DiagnosticProcessSample { pid: number; name: string; cpu_percent: number; memory_bytes: number; disk_read_bytes_per_sec: number; disk_write_bytes_per_sec: number }
export interface DiagnosticMetricPoint { timestamp: string; offset_ms: number; cpu_percent: number; memory_percent: number; available_memory_bytes: number; commit_percent: number; disk_read_bytes_per_sec: number; disk_write_bytes_per_sec: number; disk_latency_ms: number; disk_queue_length: number; network_bytes_per_sec: number; network_errors: number; network_discards: number; top_processes: DiagnosticProcessSample[] }
export interface DiagnosticHighlight { label: string; value: string; description: string; offset_ms: number; severity: "info" | "warning" | "critical" }
export interface DiagnosticProcess { pid: number; name: string; first_offset_ms: number; last_offset_ms: number; peak_offset_ms: number; sample_count: number; max_cpu_percent: number; max_memory_bytes: number; max_disk_read_bytes_per_sec: number; max_disk_write_bytes_per_sec: number }
export interface DiagnosticEvent { id: string; timestamp: string | null; offset_ms: number; channel: string; provider: string; event_id: number | null; level: number; level_label: string; summary: string; details: string; computer: string }
export interface DiagnosticWorkspace { points: DiagnosticMetricPoint[]; highlights: DiagnosticHighlight[]; processes: DiagnosticProcess[]; events: DiagnosticEvent[] }
export interface IncidentDetail { incident: Incident; pinned: boolean; observations: Observation[]; report: Report | null; raw_files: { name: string; kind: string; size_bytes: number }[]; collection: CollectionSummary; diagnostics: DiagnosticWorkspace; data_path: string }
export interface AppSettings { sample_interval_seconds: number; retention_days: number; rolling_limit_gb: number; incident_limit_gb: number; ai_mode: "disabled" | "ollama"; ollama_endpoint: string; ollama_model: string; dumps_enabled: boolean }
export interface RecoveryCandidate { detected_at: string; previous_session_started_at: string; last_sample_at: string | null }
export type CapabilityStatus = "available" | "degraded" | "unavailable" | "permission_required" | "not_installed" | "misconfigured" | "disabled";
export interface DiagnosticCapability { id: string; name: string; category: string; status: CapabilityStatus; required_now: boolean; usage: string; detail: string; path: string | null; version: string | null; requires_admin: boolean; recommendation: string | null }
export interface CapabilityReport { checked_at: string; is_elevated: boolean; available: number; attention: number; capabilities: DiagnosticCapability[] }
