export type Symptom = "system_slow" | "system_freeze" | "app_hang" | "network_slow" | "network_offline" | "display_issue" | "auto_restart" | "blue_screen" | "other";
export interface Dashboard { monitoring: boolean; uptime_seconds: number; storage_bytes: number; incident_storage_bytes: number; storage_limit_bytes: number; etw_status: string; cpu_percent: number; memory_percent: number; disk_latency_ms: number; network_kbps: number; last_sample_at: string | null; data_path: string; sensitivity_level_max: number; blackbox_cpu_percent: number; blackbox_memory_bytes: number; blackbox_disk_write_kbps: number; effective_interval_seconds: number; shortcut_status: string }
export interface IncidentDraft { symptom: Symptom; severity: "low" | "medium" | "high" | "critical"; duration_seconds: number; still_happening: boolean; description: string }
export interface Incident { schema_version: number; id: string; created_at: string; trigger_time: string; trigger_source: "manual" | "shortcut" | "tray" | "recovery" | "automatic"; symptom: Symptom; symptom_label: string; severity: string; status: string; pre_window_seconds: number; post_window_seconds: number; likely_cause: string | null; confidence: number | null; sensitivity_level: number; machine_id: string; app_version: string }
export interface Observation { id: string; title: string; description: string; source: string; category: string; offset_ms: number; severity: "info" | "warning" | "critical"; value: number | null; unit: string | null }
export interface Report { summary: string; likely_causes: { title: string; confidence: number; explanation: string; supporting_evidence_ids: string[] }[]; next_tests: { title: string; description: string; priority: number }[]; generated_by: string }
export interface TimelineTrack { label: string; points: { id: string; title: string; offset_ms: number; severity: string }[] }
export interface IncidentDetail { incident: Incident; pinned: boolean; observations: Observation[]; timeline: TimelineTrack[]; report: Report | null; raw_files: { name: string; kind: string; size_bytes: number }[]; data_path: string }
export interface AppSettings { sample_interval_seconds: number; retention_days: number; rolling_limit_gb: number; incident_limit_gb: number; ai_mode: "disabled" | "ollama"; ollama_endpoint: string; ollama_model: string; dumps_enabled: boolean }
export interface RecoveryCandidate { detected_at: string; previous_session_started_at: string; last_sample_at: string | null }
